### ISSUE TITLE
Can't create station with different parameters

### ISSUE THREAD

**Issue by shay23b** [Memphis-OS/memphis-control-plane#82]
<img width="874" alt="Screen Shot 2022-05-11 at 14 49 20" src="https://user-images.githubusercontent.com/99589346/167847492-42ec846d-1a0e-44a3-9286-3218976ca96a.png">
<img width="1064" alt="Screen Shot 2022-05-11 at 14 49 39" src="https://user-images.githubusercontent.com/99589346/167847516-63a6100a-5b16-4f7b-9513-5ec776151eca.png">

**Comment by idanasulinmemphis** [comment]
It was an issue in the CLI code, fixed and released
